// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbcfudjmvrmitziwrxlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiY2Z1ZGptdnJtaXR6aXdyeGxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTUwOTUsImV4cCI6MjA1Nzc3MTA5NX0.-F16CMhT0K1xlimKOPPDq9UEJ5X6C3x6u9N4QZ5XEJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);